'use client';

import { motion } from 'framer-motion';

interface MonthlyReportProps {
  report: string;
  month: string;
}

export default function MonthlyReport({ report, month }: MonthlyReportProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="relative bg-gradient-to-br from-accent-blue/20 via-background-secondary/80 to-accent-purple/20 backdrop-blur-sm border border-accent-blue/20 rounded-2xl p-6 overflow-hidden"
    >
      {/* Background decoration */}
      <div className="absolute top-0 right-0 w-32 h-32 bg-accent-blue/10 rounded-full blur-3xl" />
      <div className="absolute bottom-0 left-0 w-32 h-32 bg-accent-purple/10 rounded-full blur-3xl" />

      <div className="relative">
        {/* Header */}
        <div className="flex items-center gap-3 mb-4">
          <span className="text-2xl">📊</span>
          <div>
            <h3 className="text-lg font-semibold text-text-primary">Your {month} in Entertainment</h3>
            <p className="text-xs text-text-secondary">AI-generated monthly summary</p>
          </div>
        </div>

        {/* Report Content */}
        <div className="bg-background-primary/50 rounded-xl p-4 mb-4">
          <p className="text-text-secondary leading-relaxed">{report}</p>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs text-text-tertiary">
            <span className="w-2 h-2 bg-accent-blue rounded-full animate-pulse" />
            Generated by CineVerse AI
          </div>

          <button className="text-xs text-accent-blue hover:text-accent-blue/80 transition-colors flex items-center gap-1">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"
              />
            </svg>
            Share Report
          </button>
        </div>
      </div>
    </motion.div>
  );
}
